<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lookuprekening extends MY_Base
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Investasiberjangka_model');
        $this->load->model('Simpanan_model');
        $this->load->model('Simkesan_model');
        $this->load->library('form_validation');
    }

    public function lookup(){
        $active = urldecode($this->input->get('p', TRUE));
    
        switch ($active) {
            case  1:
                $this->listinvestasi();
                break;
            case  2:
                $this->listsimpanan();
                break;
            case  4:
                $this->listsimkesan();
                break;
                    
            default:
                $this->listinvestasi();
                break;
        ob_start();
        return ob_get_contents();
        ob_end_clean();
        }
    }
    
    public function listinvestasi()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        $idhtml = $this->input->get('idhtml');
        
        $investasiberjangka = $this->Investasiberjangka_model->get_limit_data( $start, $q);


        $data = array(
            'investasiberjangka_data' => $investasiberjangka,
            'idhtml' => $idhtml,
            'q' => $q,
            'start' => $start,
            'content' => 'backend/investasiberjangka/investasiberjangka_lookup',
        );
        $this->load->view($data['content'], $data);
    }

}

public function listsimpanan()
{
    $q = urldecode($this->input->get('q', TRUE));
    $start = intval($this->input->get('start'));
    $idhtml = $this->input->get('idhtml');
    $simpanan = $this->Simpanan_model->get_limit_data( $start, $q);


    $data = array(
        'simpanan_data' => $simpanan,
        'idhtml' => $idhtml,
        'q' => $q,
        'start' => $start,
        'content' => 'backend/simpanan/simpanan_lookup',
    );
    $this->load->view($data['content'], $data);
}

public function listsimkesan()
{
    $q = urldecode($this->input->get('q', TRUE));
    $start = intval($this->input->get('start'));
    $idhtml = $this->input->get('idhtml');
    
    $simkesan = $this->Simkesan_model->get_limit_data($start, $q);


    $data = array(
        'simkesan_data' => $simkesan,
        'idhtml' => $idhtml,
        'q' => $q,
        'content' => 'backend/simkesan/simkesan_lookup',
    );
    ob_start();
    $this->load->view($data['content'], $data);
    return ob_get_contents();
    ob_end_clean();
}



/* End of file Investasiberjangka.php */
/* Location: ./application/controllers/Investasiberjangka.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-26 13:55:37 */
/* http://harviacode.com */