<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Angsuranbayar_model extends CI_Model
{

    public $table = 'angsuranbayar';
    public $id = 'agb_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->where('agb_flag<',2);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

        
    // get angsuran bayar
    function get_angsuran_bayarpin($ags_id)
    {
        $where = "ags_id = '$ags_id' AND agb_flag < 2";
        $this->db->select_sum('agb_pokok');
        $this->db->select_sum('agb_bunga');
        $this->db->select_sum('agb_denda');
        $this->db->where($where);
        return $this->db->get($this->table)->row();
    }
        
    // get angsuran bayar tampil
    function get_angsuran_ags($ags_id)
    {
        $where = "agb_status > 0 AND ags_id = '$ags_id' AND agb_flag < 2";
        $this->db->select_sum('agb_pokok');
        $this->db->select_sum('agb_bunga');
        $this->db->select_sum('agb_denda');
        $this->db->where($where);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $where = "(agb_id LIKE '%$q%' ESCAPE '!' OR ags_id LIKE '%$q%' ESCAPE '!') AND agb_flag < 2";
        $this->db->where($where);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $where = "(agb_id LIKE '%$q%' ESCAPE '!' OR ags_id LIKE '%$q%' ESCAPE '!') AND agb_flag < 2";
        $this->db->where($where);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update data angsuran
    function updateangsuran($ags_id, $data)
    {
        $this->db->where('ags_id =', $ags_id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Angsuranbayar_model.php */
/* Location: ./application/models/Angsuranbayar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-06 22:43:38 */
/* http://harviacode.com */