<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kasbon_model extends CI_Model
{

    public $table = 'kasbon';
    public $id = 'ksb_no';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->where('ksb_flag<',2);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    // get data rekap
    function get_rekap($j,$w,$f)
    {
        $where = "wil_kode = $w AND ksb_jenis = $j AND ksb_flag < 2";
        $this->db->where($where);
        $this->db->where("DATE_FORMAT(ksb_tanggal, '%Y-%m-%d') = '$f'");
        return $this->db->get($this->table)->row();
    }
    // get data tunai
    function get_tunai($j,$w,$now,$lalu,$f,$t,$month)
    {
        if ($w != NULL) {
            $this->db->where("wil_kode = $w AND ksb_jenis = $j");
        }
        if ($now != NULL){
            $this->db->where("DATE_FORMAT(ksb_tanggal, '%Y-%m-%d') = '$now'");
        }
        if ($f != NULL) {
            $this->db->where("DATE_FORMAT(ksb_tanggal, '%Y-%m-%d') >= '$f'");
        }
        if ($t != NULL) {
            $this->db->where("DATE_FORMAT(ksb_tanggal, '%Y-%m-%d') <= '$t'");
        }
        if ($lalu != NULL) {
            $this->db->where("DATE_FORMAT(ksb_tanggal, '%Y-%m-%d') < '$lalu'");
        }
        if ($month != NULL) {
            $this->db->where("DATE_FORMAT(ksb_tanggal, '%Y-%m') = '$month'");
        }
        $this->db->where("ksb_flag < 2");
        $this->db->select_sum('ksb_masuk');
        $this->db->select_sum('ksb_keluar');
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $where = "(wil_kode LIKE '%$q%' ESCAPE '!' OR kar_kode LIKE '%$q%' ESCAPE '!') AND ksb_flag < 2";
        $this->db->where($where);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $where = "(wil_kode LIKE '%$q%' ESCAPE '!' OR kar_kode LIKE '%$q%' ESCAPE '!') AND ksb_flag < 2";
        $this->db->where($where);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kasbon_model.php */
/* Location: ./application/models/Kasbon_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-17 05:50:15 */
/* http://harviacode.com */