<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penarikansimkesan_model extends CI_Model
{

    public $table = 'penarikansimkesan';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('pns_id', $q);
	$this->db->or_like('sik_kode', $q);
	$this->db->or_like('jps_id', $q);
	$this->db->or_like('pns_tglpenarikan', $q);
	$this->db->or_like('pns_jmlsimkesan', $q);
	$this->db->or_like('pns_jmlpenarikan', $q);
	$this->db->or_like('pns_catatan', $q);
	$this->db->or_like('pns_tgl', $q);
	$this->db->or_like('pns_flag', $q);
	$this->db->or_like('pns_info', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('pns_id', $q);
	$this->db->or_like('sik_kode', $q);
	$this->db->or_like('jps_id', $q);
	$this->db->or_like('pns_tglpenarikan', $q);
	$this->db->or_like('pns_jmlsimkesan', $q);
	$this->db->or_like('pns_jmlpenarikan', $q);
	$this->db->or_like('pns_catatan', $q);
	$this->db->or_like('pns_tgl', $q);
	$this->db->or_like('pns_flag', $q);
	$this->db->or_like('pns_info', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Penarikansimkesan_model.php */
/* Location: ./application/models/Penarikansimkesan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-26 14:00:01 */
/* http://harviacode.com */