<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengkodean_model extends CI_Model
{

    public $table = 'ahliwarissimkesan';

    function __construct()
    {
        parent::__construct();
    }

    // get all

    // get data by id
    
    // get total rows
    
    // get data with limit and search
    
    // insert data
    
    // update data
    
    // delete data
    
}

/* End of file Ahliwarissimkesan_model.php */
/* Location: ./application/models/Ahliwarissimkesan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-26 05:39:31 */
/* http://harviacode.com */