<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tunai_kasir_model extends CI_Model
{

    public $table = 'tunai_kasir';
    public $id = 'tun_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->where('tun_flag<',2);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

	function get_kasir($f,$t,$lalu,$month){
        if ($f != NULL) {
            $this->db->where("DATE_FORMAT(tun_tanggal, '%Y-%m-%d') >= '$f'");
        }
        if ($t != NULL) {
            $this->db->where("DATE_FORMAT(tun_tanggal, '%Y-%m-%d') <= '$t'");
        }
        if ($lalu != NULL) {
            $this->db->where("DATE_FORMAT(tun_tanggal, '%Y-%m-%d') < '$lalu'");
        }
        if ($month != NULL) {
            $this->db->where("DATE_FORMAT(tun_tanggal, '%Y-%m') = '$month'");
        }
        $this->db->where('tun_flag < 2');
        $this->db->select_sum('tun_jumlah');
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $where = "(tun_jenis LIKE '%$q%' ESCAPE '!' OR tun_kantor LIKE '%$q% ESCAPE '!') AND tun_flag < 2";
        $this->db->where($where);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $where = "(tun_jenis LIKE '%$q%' ESCAPE '!' OR tun_kantor LIKE '%$q% ESCAPE '!') AND tun_flag < 2";
        $this->db->where($where);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tunai_kasir_model.php */
/* Location: ./application/models/Tunai_kasir_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-29 06:45:36 */
/* http://harviacode.com */